// Committed DEMO dataset so the app runs with zero setup (open index.html).
// Real data overrides this when review/study-data.js is generated from a vault.
window.STUDY_DATA = {
  generatedAt: "2026-06-29T00:00:00.000Z",
  vault: "sample",
  concepts: [
    { id: "crux", title: "The crux", type: "concept", tags: ["mental-model", "career"],
      summary: "The single biggest obstacle on the path to the top (a rock-climbing term). Identify it, focus there first, and iterate — don't spread effort evenly across the easy moves.",
      links: ["outcome-oriented-mindset", "prioritisation"] },
    { id: "outcome-oriented-mindset", title: "Outcome-oriented mindset", type: "concept", tags: ["mental-model", "career"],
      summary: "Hold the goal in mind and work backward to reach it; cut the noise and engage only what is relevant to the outcome.",
      links: ["crux", "prioritisation", "atomic-commits"] },
    { id: "prioritisation", title: "Prioritisation", type: "concept", tags: ["mental-model", "career"],
      summary: "Deciding what weighs more — and deliberately not giving attention to the rest.",
      links: ["crux", "outcome-oriented-mindset"] },
    { id: "architectural-design-scale", title: "Architecture follows scale", type: "concept", tags: ["systems", "engineering"],
      summary: "Scale decides the choice of frameworks: build quickly with popular, well-documented tools where speed matters; build for scale only where it is justified.",
      links: ["rpc", "migration-is-hard"] },
    { id: "migration-is-hard", title: "Migration is hard", type: "concept", tags: ["systems", "engineering"],
      summary: "Migrating a stack (e.g. Node to Go) takes years and rarely fully completes — which is exactly why the right initial architecture matters.",
      links: ["architectural-design-scale"] },
    { id: "rpc", title: "RPC", type: "concept", tags: ["cs-fundamentals", "distributed-systems"],
      summary: "Call a function that runs in another process or machine as if it were local; the network plumbing (serialize, send, execute, return) is hidden behind ordinary call syntax.",
      links: ["architectural-design-scale", "database-cache-consistency"] },
    { id: "database-cache-consistency", title: "DB ↔ cache consistency", type: "concept", tags: ["system-design", "caching"],
      summary: "A cache fronts a slower database for speed; on writes the two can diverge and serve stale reads unless you invalidate carefully.",
      links: ["rpc", "b-tree-vs-b-plus-tree"] },
    { id: "b-tree-vs-b-plus-tree", title: "B-tree vs B+ tree", type: "concept", tags: ["data-structures", "databases"],
      summary: "Self-balancing multi-way search trees built for disk storage; B+ trees keep all values in linked leaves (great for range scans), while B-trees also store values in internal nodes.",
      links: ["database-cache-consistency"] },
    { id: "atomic-commits", title: "Atomic commits", type: "concept", tags: ["engineering", "workflow"],
      summary: "Each commit is one self-contained change — which makes review, revert, and bisect dramatically easier.",
      links: ["outcome-oriented-mindset"] },
    { id: "ai-feedback-loops", title: "AI feedback loops", type: "concept", tags: ["ai", "engineering"],
      summary: "Give an agent a way to correct itself end-to-end; a statically and strongly typed language surfaces errors the loop can catch before a human has to.",
      links: ["hiring-game"] },
    { id: "hiring-game", title: "The hiring game", type: "concept", tags: ["career", "interview-prep"],
      summary: "Interviews — LeetCode, rigorous question sets — are games to be played well; you can't change the game if you are not in the system.",
      links: ["ai-feedback-loops"] },
  ],
  cards: [
    { id: "crux::def", deck: "concept", source: "crux", front: "What does “the crux” mean, and how should you use it?", back: "The single biggest obstacle on the path to the top (from rock climbing). Identify it, focus there first, and iterate." },
    { id: "outcome-oriented-mindset::def", deck: "concept", source: "outcome-oriented-mindset", front: "What is an outcome-oriented mindset?", back: "Keep the goal in mind, work backward, cut the noise, and engage only what's relevant to the outcome." },
    { id: "prioritisation::def", deck: "concept", source: "prioritisation", front: "What's the core of prioritisation?", back: "Knowing what weighs more — and deliberately not giving attention to the rest." },
    { id: "architectural-design-scale::def", deck: "concept", source: "architectural-design-scale", front: "What decides your choice of frameworks?", back: "Scale. Use popular, well-documented tools for speed; build for scale only where it is justified." },
    { id: "migration-is-hard::def", deck: "concept", source: "migration-is-hard", front: "Why does the initial architecture matter so much?", back: "Because migrating a stack (e.g. Node→Go) takes years and rarely fully completes." },
    { id: "rpc::def", deck: "concept", source: "rpc", front: "What is RPC?", back: "Calling a function in another process or machine as if it were local — the network plumbing is hidden behind ordinary call syntax." },
    { id: "rpc::gotcha", deck: "concept", source: "rpc", front: "What's the RPC gotcha?", back: "It looks like a local call but isn't — latency, partial failure, serialization cost, and contract versioning all leak through." },
    { id: "database-cache-consistency::def", deck: "concept", source: "database-cache-consistency", front: "Why can a cache serve stale data?", back: "On writes the cache and DB diverge; without an invalidation strategy, reads go stale." },
    { id: "b-tree-vs-b-plus-tree::def", deck: "concept", source: "b-tree-vs-b-plus-tree", front: "B-tree vs B+ tree — the key difference?", back: "B+ trees keep all values in linked leaves (ideal for range scans); B-trees also store values in internal nodes." },
    { id: "atomic-commits::def", deck: "concept", source: "atomic-commits", front: "What is an atomic commit, and why bother?", back: "One self-contained change per commit — making review, revert, and bisect much easier." },
    { id: "ai-feedback-loops::def", deck: "concept", source: "ai-feedback-loops", front: "What makes AI agents self-correct well?", back: "An end-to-end feedback loop plus a statically/strongly typed language that surfaces errors for the loop to catch." },
    { id: "hiring-game::def", deck: "concept", source: "hiring-game", front: "How should you treat technical interviews?", back: "As games to play well (LeetCode, rigor) — you can't change the game if you're not in the system." },
  ],
  edges: [
    { source: "crux", target: "outcome-oriented-mindset" },
    { source: "crux", target: "prioritisation" },
    { source: "outcome-oriented-mindset", target: "prioritisation" },
    { source: "outcome-oriented-mindset", target: "atomic-commits" },
    { source: "architectural-design-scale", target: "rpc" },
    { source: "architectural-design-scale", target: "migration-is-hard" },
    { source: "rpc", target: "database-cache-consistency" },
    { source: "database-cache-consistency", target: "b-tree-vs-b-plus-tree" },
    { source: "ai-feedback-loops", target: "hiring-game" },
  ],
};
