// Committed synthetic DEMO dataset so the app runs with zero setup (open index.html).
window.STUDY_DATA = {
  generatedAt: "2026-06-29T00:00:00.000Z",
  vault: "sample",
  concepts: [
    { id: "local-first-pipeline", title: "Local-first knowledge pipeline", type: "concept", tags: ["local-first", "workflow"],
      summary: "A knowledge workflow that keeps source material on the user's machine, converts it into durable local files, and makes every later step inspectable.",
      links: ["provenance", "immutable-raw-sources", "note-conversion"] },
    { id: "provenance", title: "Provenance", type: "concept", tags: ["trust", "metadata"],
      summary: "Metadata that records where material came from, when it was captured, and how it was transformed so derived knowledge remains traceable.",
      links: ["local-first-pipeline", "immutable-raw-sources", "verification-gates"] },
    { id: "immutable-raw-sources", title: "Immutable raw sources", type: "concept", tags: ["data-integrity", "workflow"],
      summary: "Captured source files stay unchanged; corrections and synthesis happen in derived files so the original evidence remains available for comparison.",
      links: ["local-first-pipeline", "provenance", "safe-agent-workflows"] },
    { id: "note-conversion", title: "Note conversion", type: "concept", tags: ["conversion", "markdown"],
      summary: "The deterministic transformation of note text and attachments into portable Markdown plus local assets without changing their intended reading order.",
      links: ["local-first-pipeline", "asset-order-preservation", "deterministic-identifiers"] },
    { id: "asset-order-preservation", title: "Asset order preservation", type: "concept", tags: ["conversion", "multimodal"],
      summary: "Images and other attachments remain beside the text they explain, preserving the source note's sequence and meaning after conversion.",
      links: ["note-conversion", "verification-gates"] },
    { id: "deterministic-identifiers", title: "Deterministic identifiers", type: "concept", tags: ["data-model", "stability"],
      summary: "Stable IDs derived from durable inputs keep concepts, cards, and review history connected across repeatable regeneration runs.",
      links: ["note-conversion", "study-review-loop"] },
    { id: "study-review-loop", title: "Study and review loop", type: "concept", tags: ["learning", "review"],
      summary: "A cycle that turns synthesized concepts into prompts, records recall quality, and schedules the next review rather than leaving notes unread.",
      links: ["deterministic-identifiers", "spaced-repetition", "concept-graph"] },
    { id: "spaced-repetition", title: "Spaced repetition", type: "concept", tags: ["learning", "scheduling"],
      summary: "A review strategy that increases intervals after successful recall and shortens them after difficulty, concentrating effort where memory is weakest.",
      links: ["study-review-loop"] },
    { id: "concept-graph", title: "Concept graph", type: "concept", tags: ["learning", "relationships"],
      summary: "A navigable map of concepts and their explicit links that helps reviewers move between related ideas and spot isolated material.",
      links: ["study-review-loop", "provenance"] },
    { id: "safe-agent-workflows", title: "Safe agent workflows", type: "concept", tags: ["agents", "safety"],
      summary: "Bounded automation that limits scope, preserves user-owned source material, exposes changes for review, and stops at irreversible actions.",
      links: ["immutable-raw-sources", "verification-gates"] },
    { id: "verification-gates", title: "Verification gates", type: "concept", tags: ["agents", "quality"],
      summary: "Objective checks such as syntax validation, referential integrity, and diff review that must pass before an automated change is considered complete.",
      links: ["provenance", "asset-order-preservation", "safe-agent-workflows"] },
  ],
  cards: [
    { id: "local-first-pipeline::def", deck: "concept", source: "local-first-pipeline", front: "What makes a knowledge pipeline local-first?", back: "Source material and derived files stay on the user's machine, and each transformation remains inspectable." },
    { id: "provenance::def", deck: "concept", source: "provenance", front: "What does provenance record?", back: "The material's origin, capture time, and transformation history so derived knowledge can be traced back." },
    { id: "immutable-raw-sources::def", deck: "concept", source: "immutable-raw-sources", front: "Why keep raw source files immutable?", back: "They preserve the original evidence; corrections and synthesis belong in separate derived files." },
    { id: "note-conversion::def", deck: "concept", source: "note-conversion", front: "What should deterministic note conversion preserve?", back: "Text, attachments, intended reading order, and portable output paths." },
    { id: "asset-order-preservation::def", deck: "concept", source: "asset-order-preservation", front: "Why does attachment order matter during conversion?", back: "An image's surrounding text supplies context, so moving it can change the note's meaning." },
    { id: "asset-order-preservation::check", deck: "workflow", source: "asset-order-preservation", front: "How can an export verify asset order?", back: "Use an interleaved text-and-image fixture and assert that each generated embed falls between the expected paragraphs." },
    { id: "deterministic-identifiers::def", deck: "concept", source: "deterministic-identifiers", front: "Why use deterministic identifiers for study cards?", back: "Stable IDs keep saved review history attached when the dataset is regenerated." },
    { id: "study-review-loop::def", deck: "concept", source: "study-review-loop", front: "What closes the study and review loop?", back: "Prompting recall, recording the result, and scheduling a later review." },
    { id: "spaced-repetition::def", deck: "concept", source: "spaced-repetition", front: "How does spaced repetition allocate study time?", back: "It lengthens intervals after successful recall and shortens them after difficulty." },
    { id: "concept-graph::def", deck: "concept", source: "concept-graph", front: "What does a concept graph reveal?", back: "Explicit relationships between ideas and concepts that have become isolated." },
    { id: "safe-agent-workflows::def", deck: "workflow", source: "safe-agent-workflows", front: "What makes an agent workflow safe?", back: "Bounded scope, preserved source material, reviewable diffs, objective checks, and stops before irreversible actions." },
    { id: "verification-gates::def", deck: "workflow", source: "verification-gates", front: "Name three useful verification gates for a generated study dataset.", back: "JavaScript syntax validation, edge/card referential integrity, and a clean scoped diff review." },
    { id: "verification-gates::principle", deck: "workflow", source: "verification-gates", front: "Why must verification happen before completion is claimed?", back: "Fresh evidence distinguishes a checked result from an assumption about what should work." },
  ],
  edges: [
    { source: "local-first-pipeline", target: "provenance" },
    { source: "local-first-pipeline", target: "immutable-raw-sources" },
    { source: "local-first-pipeline", target: "note-conversion" },
    { source: "provenance", target: "verification-gates" },
    { source: "immutable-raw-sources", target: "safe-agent-workflows" },
    { source: "note-conversion", target: "asset-order-preservation" },
    { source: "note-conversion", target: "deterministic-identifiers" },
    { source: "deterministic-identifiers", target: "study-review-loop" },
    { source: "study-review-loop", target: "spaced-repetition" },
    { source: "study-review-loop", target: "concept-graph" },
    { source: "concept-graph", target: "provenance" },
    { source: "asset-order-preservation", target: "verification-gates" },
    { source: "safe-agent-workflows", target: "verification-gates" },
  ],
};
