import XCTest
@testable import AppleNotestoX

final class StudyDataParseTests: XCTestCase {
    private let sample = """
    // GENERATED by review/generate.mjs from Personal_LLM_Wiki — do not edit by hand.
    window.STUDY_DATA = {
      "generatedAt": "2026-06-30T08:58:40.332Z",
      "vault": "Personal_LLM_Wiki",
      "concepts": [
        {"id":"a","title":"Alpha","type":"concept","summary":"","tags":[],"links":["b","c"]},
        {"id":"b","title":"Beta","type":"concept","summary":"","tags":[],"links":["a"]},
        {"id":"c","title":"Gamma","type":"concept","summary":"","tags":[],"links":["a"]}
      ],
      "cards": [ {"id":"a::def","deck":"concept","front":"?","back":".","source":"a"} ],
      "edges": [ {"source":"a","target":"b"}, {"source":"a","target":"c"} ]
    };
    """

    func testParsesCountsAndGeneratedAt() {
        let d = StudyData.parse(sample)
        XCTAssertNotNil(d)
        XCTAssertEqual(d?.conceptCount, 3)
        XCTAssertEqual(d?.cardCount, 1)
        XCTAssertEqual(d?.edgeCount, 2)
        XCTAssertEqual(d?.generatedAt, "2026-06-30T08:58:40.332Z")
    }

    func testTopConceptsRankedByEdgeDegree() {
        // "a" touches both edges (degree 2); b and c degree 1 → Alpha first.
        XCTAssertEqual(StudyData.parse(sample, topN: 1)?.topConcepts, ["Alpha"])
    }

    func testMalformedReturnsNil() {
        XCTAssertNil(StudyData.parse("not javascript"))
        XCTAssertNil(StudyData.parse(""))
    }
}
